# Generated by Django 4.0.3 on 2022-03-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('idaddress', models.IntegerField(primary_key=True, serialize=False)),
                ('addresscol', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
