# Generated by Django 4.0.3 on 2022-06-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_addres_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('idstatus', models.IntegerField(primary_key=True, serialize=False)),
                ('statusname', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('idten', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('data1', models.DateTimeField()),
                ('data2', models.DateTimeField()),
                ('inn', models.IntegerField()),
                ('sum0', models.IntegerField()),
                ('prepayment', models.IntegerField()),
                ('provision', models.IntegerField()),
                ('region', models.TextField()),
                ('source', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='addres',
            options={'managed': False, 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адресы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False, 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='tender',
            options={'managed': False, 'verbose_name': 'Тендер', 'verbose_name_plural': 'Тендеры'},
        ),
    ]
