# Generated by Django 4.0.3 on 2022-06-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0003_status_test1_alter_addres_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='inn',
            field=models.TextField(),
        ),
    ]
