# Generated by Django 4.0.3 on 2022-06-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0004_alter_test1_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='prepayment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test1',
            name='provision',
            field=models.TextField(),
        ),
    ]
