# Generated by Django 4.0.3 on 2022-06-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0005_alter_test1_prepayment_alter_test1_provision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='sum0',
            field=models.BigIntegerField(),
        ),
    ]
