# Generated by Django 4.0.3 on 2022-06-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0006_alter_test1_sum0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='inn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test1',
            name='prepayment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test1',
            name='provision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test1',
            name='sum0',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
