# Generated by Django 4.0.3 on 2022-06-08 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0007_alter_test1_inn_alter_test1_prepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='watcher.status'),
        ),
    ]
