# Generated by Django 4.0.3 on 2022-06-08 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0008_test1_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='watcher.region'),
        ),
    ]
