# Generated by Django 4.0.3 on 2022-06-08 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0009_alter_test1_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='watcher.category'),
        ),
    ]
