# Generated by Django 4.0.3 on 2022-06-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0010_alter_test1_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сustomer',
            fields=[
                ('idcust', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
    ]
