# Generated by Django 4.0.3 on 2022-06-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0011_сustomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='сustomer',
            old_name='name',
            new_name='namec',
        ),
    ]
