# Generated by Django 4.0.3 on 2022-06-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0013_rename_namec_сustomer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сustomer',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
