# Generated by Django 4.0.3 on 2022-06-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0014_alter_сustomer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='asdasd',
            fields=[
                ('idcust', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Сustomer',
        ),
    ]
