# Generated by Django 4.0.3 on 2022-06-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0015_asdasd_delete_сustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inn',
            fields=[
                ('idcust', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='asdasd',
        ),
    ]
