# Generated by Django 4.0.3 on 2022-06-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0016_inn_delete_asdasd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inn',
            old_name='idcust',
            new_name='idi',
        ),
        migrations.AddField(
            model_name='inn',
            name='inn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
