# Generated by Django 4.0.3 on 2022-06-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0017_rename_idcust_inn_idi_inn_inn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'managed': False, 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адресы'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'managed': False, 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'managed': False, 'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='test1',
            options={'managed': False},
        ),
    ]
