# Generated by Django 4.0.3 on 2022-06-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0018_alter_application_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test1',
            options={},
        ),
    ]
